DROP TABLE `agentes`;--> statement-breakpoint
DROP TABLE `auditoria`;--> statement-breakpoint
DROP TABLE `calculos`;--> statement-breakpoint
DROP TABLE `certificacoes`;--> statement-breakpoint
DROP TABLE `consignados`;--> statement-breakpoint
DROP TABLE `consorcios`;--> statement-breakpoint
DROP TABLE `contasCorrentes`;--> statement-breakpoint
DROP TABLE `documentacao`;--> statement-breakpoint
DROP TABLE `extratoConsignados`;--> statement-breakpoint
DROP TABLE `extratoConsorcios`;--> statement-breakpoint
DROP TABLE `extratoContas`;--> statement-breakpoint
DROP TABLE `extratoOurocap`;--> statement-breakpoint
DROP TABLE `fornecedores`;--> statement-breakpoint
DROP TABLE `loginAttempts`;--> statement-breakpoint
DROP TABLE `mensagens`;--> statement-breakpoint
DROP TABLE `ourocap`;--> statement-breakpoint
DROP TABLE `pagamentos`;--> statement-breakpoint
DROP TABLE `producaoBb`;--> statement-breakpoint
DROP TABLE `seguros`;--> statement-breakpoint
DROP TABLE `sessoes`;--> statement-breakpoint
DROP TABLE `tabelasComissao`;